// Generated by QCLang Phase 1.5 (QIR-to-QASM)
// Module: main
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg c[2];

// Initialization gates

// Function: main
  // Block 0
  measure q[0] -> c[0];
  h q[2];
  measure q[2] -> c[1];

