// Generated by QCLang Phase 1.5 (QIR-to-QASM)
// Module: main
OPENQASM 2.0;
include "qelib1.inc";

qreg q[1];
creg c[1];

// Initialization gates

// Function: test_array
  // Block 0

// Function: main
  // Block 0

