// Generated by QCLang Phase 1.5 (QIR-to-QASM)
// Module: main
OPENQASM 2.0;
include "qelib1.inc";

qreg q[1];
creg c[1];

// Initialization gates

// Function: main
  // Block 0
  h q[0];
  x q[0];

