// Generated by QCLang Phase 1.5 (QIR-to-QASM)
// Module: main
OPENQASM 2.0;
include "qelib1.inc";

qreg q[11];
creg c[3];

// Initialization gates
x q[7]; // Initialize |1>
x q[9]; // Initialize |1>

// Function: basic_test
  // Block 0
  h q[0];
  x q[1];
  measure q[0] -> c[0];
  measure q[1] -> c[1];
  measure q[2] -> c[2];

