// Generated by QCLang Phase 1.5 (QIR-to-QASM)
// Module: main
OPENQASM 2.0;
include "qelib1.inc";

qreg q[3];
creg c[1];

// Initialization gates
x q[0]; // Initialize |1>

// Function: teleport
  // Block 0

// Function: main
  // Block 0

